### ISSUE TITLE
Any way to get everything with request?

### ISSUE THREAD

**Issue by sumanla13a** [prolificinteractive/node-html-to-json#2]
Is there any way of getting every tags, every attributes from requesting a url?

htmlToJson.request('http://prolificinteractive.com/team', { //some option to get everything
     }, function (err, result) {
      console.log(result);
    });

**Comment by prolificeric** [comment]
You'd want to write a recursive function that takes an element and returns its tagName and attributes, then maps its children through that same function. For example:

```
function getTree ($el, $) {
    return {
      tagName: $el[0].tagName,
      attributes: $el[0].getAttributes(), // Not how you do this, just pseudo-code
      children: $el.children().map((child) => getTree($(child)))
   };
}
```
